[phases.setup]
nixPkgs = ["...", "nodejs_20", "openssl"]

[phases.build]
cmds = [
  "npm install --include=dev",
  "cd apps/backend",
  "npx prisma generate",
  "npm run build"
]

[variables]
NPM_CONFIG_PRODUCTION = "false"
HUSKY = "0"
