[phases.setup]
nixPkgs = ["...", "nodejs_20", "openssl"]

[phases.build]
cmds = [
  "npm install --include=dev",
  "npx prisma generate --schema apps/backend/prisma/schema.prisma",
  "npm -w backend run build"
]

[variables]
NPM_CONFIG_PRODUCTION = "false"
HUSKY = "0"
