[phases.setup]
nixPkgs = ["...", "nodejs_20", "openssl"]

[phases.build]
cmds = [
  "npm install",
  "cd apps/backend",
  "npx prisma generate",
  "npm run build"
]

[phases.start]
cmds = ["cd apps/backend && npm run start:prod"]

[variables]
NODE_ENV = "production"
